### PR TITLE
fix: binary upload as base 64 content

### LINKED ISSUE #48: Using upload inside docker_container with binary files always forces a destroy
### Terraform Version

``` tf11 --version
Terraform v0.11.4
+ provider.cloudflare v0.1.0
+ provider.digitalocean v0.1.3
+ provider.docker v0.1.1
+ provider.mysql v0.1.0
+ provider.template v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `docker_container`

### Terraform Configuration Files
```hcl
resource docker_container "docker-file-test" {
  name  = "docker-file-test"
  image = "${docker_image.docker-file-test.latest}"

  upload {
    content = "${file("${path.module}/files/1.txt")}"

    file = "/var/1.txt"
  }
}
```

### Debug Output

Both outputs are after running 1 apply with the relevant file

#### Output with plain text file

```bash
$ cat 1.txt && sha1sum 1.txt 
894fc3f56edf2d3a4c5fb5cb71df910f958a2ed8  -
4f459664a6b39e5f2cf595b37cfdfcb7d9740c17  1.txt
$ tf11 plan  --target module.docker-file-test
..
No changes. Infrastructure is up-to-date.
```

#### Output with a 2-byte binary file

```bash
cat 1.txt && echo && sha1sum 1.txt 
ñG
143fbaf9b82ba1b4f20faad9505e685e4d3639a4  1.txt
tf11 plan  --target module.docker-file-test
Terraform will perform the following actions:

-/+ module.docker-file-test.docker_container.docker-file-test (new resource required)
      id:                        "aba876dfa85d605266cabaadda63523db11bfa600d12c61c4731040b41593903" => <computed> (forces new resource)
      bridge:                    "" => <computed>
      gateway:                   "172.17.0.1" => <computed>
      image:                     "sha256:73acd1f0cfadf6f56d30351ac633056a4fb50d455fd95b229f564ff0a7adecda" => "sha256:73acd1f0cfadf6f56d30351ac633056a4fb50d455fd95b229f564ff0a7adecda"
      ip_address:                "172.17.0.26" => <computed>
      ip_prefix_length:          "16" => <computed>
      log_driver:                "json-file" => "json-file"
      must_run:                  "true" => "true"
      name:                      "docker-file-test" => "docker-file-test"
      restart:                   "no" => "no"
      upload.#:                  "1" => "1"
      upload.2067081083.content: "�G" => "" (forces new resource)
      upload.2067081083.file:    "/var/1.txt" => "" (forces new resource)
      upload.277341835.content:  "" => "\xf1G" (forces new resource)
      upload.277341835.file:     "" => "/var/1.txt" (forces new resource)


Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

```

### Expected Behavior

The second plan should show `No Changes`, since the file on disk is matching the file on the container. This is important if you are uploading binaries to the container. In my case, this happens to be image files (logos/banners etc), which do not change, but give me dirty plans.

### Actual Behavior

A dirty plan is generated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Add the attached `1.txt` file to any docker_container using the same upload syntax as above.
2. Run a apply to make sure that the file uploads
3. Run another plan

I've seen the comment on the code:

```go
// This is intentional. The container is mutated once, and never updated later.
// New configuration forces a new deployment, even with the same binaries.
```

but it applies unequally to binary/text files which is quite confusing.

### PR DESCRIPTION
**Pull request by mavogel**
### Current fixes
- [x] Fixes #48 by introducing a new `content_base64` property for the upload of larger binaries into a container
- [x] I still need to fix the issue by checking the state of the `upload` set. Waiting for feedback => will be addressed separately in https://github.com/hashicorp/terraform-plugin-sdk/issues/196

### Steps to reproduces
- check out the `fix-binary-upload` branch, uncomment the [lines](https://github.com/terraform-providers/terraform-provider-docker/pull/194/files#diff-6338b0235b8cfe8182bac07219a91c40R616) of the `resource_docker_container_test.go` file and run
```sh
make testacc_setup
TF_LOG=INFO TF_ACC=1 go test -v ./docker -run ^TestAccDockerContainer_upload$ -timeout 360s
```
- you will see in the log of the test, so the properties are actually written into the state
```
  upload.# = 1
  upload.0.content = foo
  upload.0.content_base64 = 
  upload.0.executable = true
  upload.0.file = /terraform/test.txt
```
- but actually the check fails:
```go
resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDockerContainerUploadConfig,
				Check: resource.ComposeTestCheckFunc(
					testAccContainerRunning("docker_container.foo", &c),
					testCheck,
					resource.TestCheckResourceAttr("docker_container.foo", "name", "tf-test"),
					resource.TestCheckResourceAttr("docker_container.foo", "upload.#", "1"),
					// TODO mavogel: although they are in the state they are not found... check fails
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.content", "foo"),
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.content_base64", ""),
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.executable", "true"),
					// resource.TestCheckResourceAttr("docker_container.foo", "upload.0.file", "/terraform/test.txt"),
				),
			},
		},
	})
```

### CODE REVIEW

File: docker/resource_docker_container_funcs.go [hunk 1]
```diff
@@ -382,6 +383,18 @@ func resourceDockerContainerCreate(d *schema.ResourceData, meta interface{}) err
 		var mode int64
 		for _, upload := range v.(*schema.Set).List() {
 			content := upload.(map[string]interface{})["content"].(string)
+			contentBase64 := upload.(map[string]interface{})["content_base64"].(string)
+			if content == "" && contentBase64 == "" {
```
Comment (mbfrahry) [inline docker/resource_docker_container_funcs.go]: It looks like you were trying to do `ConflictsWith` between these two attributes so we add the flipped version of this logic as well to make sure that a user doesn't submit both types of content. Something like 
```suggestion
			if content != "" && contentBase64 != "" {
			  return fmt.Errorf("Error with upload content: only one of `content` or `content_base64` can be specified")
			  }
```

File: docker/resource_docker_container_test.go [hunk 2]
```diff
@@ -610,6 +610,98 @@ func TestAccDockerContainer_upload(t *testing.T) {
 				Check: resource.ComposeTestCheckFunc(
 					testAccContainerRunning("docker_container.foo", &c),
 					testCheck,
+					resource.TestCheckResourceAttr("docker_container.foo", "name", "tf-test"),
+					resource.TestCheckResourceAttr("docker_container.foo", "upload.#", "1"),
+					// NOTE mavogel: current the terraform-plugin-sdk it's likely that
```
Comment (mbfrahry) [inline docker/resource_docker_container_test.go]: Can this resource support import? If so, we can add an import test step that can check all these values instead of manually figuring out the Set hashcode.

Comment (mavogel) [reply docker/resource_docker_container_test.go]: A PR for imports #196 is also in progress and I'll update then test then. Thanks for the hint

File: docker/resource_docker_container_funcs.go (hunk 1 above)
Comment (mbfrahry) [reply docker/resource_docker_container_funcs.go]: Also, I saw my comment was a suggestion to override the current implementation. I'll edit it and suggest doing both if statements for maximum validation coverage

Comment (mavogel) [reply docker/resource_docker_container_funcs.go]: Yes, makes totally sense. I added a check for at least one of the `content` properties is set and that not both are set + test. Now it looks good

Comment (mbfrahry) [reply docker/resource_docker_container_funcs.go]: Looks great!
